language: "zh"

pipeline:
- name: "tokenizer_bert"
- name: "intent_featurizer_bert"
  spell_checker: "mask"
  spell_checker_score: 1
  BERT_BASE_DIR: "./bert_pretrain_model/uncased_L-12_H-768_A-12"
  mul_similar_matrix: False